spring.application.name=impaintor
server.servlet.context-path=/api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/impaintor}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
app.debug-errors=${APP_DEBUG_ERRORS:false}
logging.level.org.springframework.web.socket=${APP_WS_LOG_LEVEL:INFO}
logging.level.org.springframework.messaging.simp.stomp=${APP_WS_LOG_LEVEL:INFO}
logging.level.org.springframework.web.socket.sockjs=${APP_WS_LOG_LEVEL:INFO}

spring.websocket.path=/ws
